MIN_IDENTIFIER = 1
MIN_ITEM_QUANTITY = 1
MAX_ITEM_QUANTITY = 50
MIN_PAGE_LIMIT = 1
MAX_PAGE_LIMIT = 50
MIN_PAGE_OFFSET = 0

MIN_TOP_PRODUCT_LIMIT = 1
MAX_TOP_PRODUCT_LIMIT = 20
MIN_RULE_LIMIT = 1
MAX_RULE_LIMIT = 500
MIN_ANALYTICS_DAYS = 7
MAX_ANALYTICS_DAYS = 365

MIN_RECOMMENDATION_LIMIT = 1
MAX_RECOMMENDATION_LIMIT = 10
